### ISSUE TITLE
Not works with Geeetech Prusa I3 Pro B

### ISSUE THREAD

**Issue by MathieuAndrade** [jneilliii/OctoPrint-BedLevelVisualizer#109]
Hello ! 

I'm trying to use this plugin but it does not work with my Prusa clone 🙁 

I'm use this Gcode commands => 
````
G28
M155 S30
@BEDLEVELVISUALIZER
G29 T
M155 S3
````

**Note: I have tested with the G29 T1 and T2 also.**

Here is the format data i get => 
````
Send: G28
Send: M155 S30
Recv: ok
Recv: ok
Send: G29 T1
Send: M155 S3
Recv: Bed x: 30.00 y: 20.00 z: 0.10
Recv: Bed x: 107.00 y: 20.00 z: 0.22
Recv: Bed x: 184.00 y: 20.00 z: 0.36
Recv: Bed x: 185.00 y: 86.00 z: 0.26
Recv: Bed x: 108.00 y: 86.00 z: 0.02
Recv: Bed x: 31.00 y: 86.00 z: -0.06
Recv: Bed x: 30.00 y: 152.00 z: -0.26
Recv: Bed x: 107.00 y: 152.00 z: -0.11
Recv: Bed x: 184.00 y: 152.00 z: 0.05
Recv: Eqn coefficients: a: 0.00 b: -0.00 d: 0.07
Recv: planeNormal x: -0.00 y: 0.00 z: 1.00
Recv: ok
[...]
Recv: echo:endstops hit:  Z:0.05
Recv: ok
````

And the error message => 

![image](https://user-images.githubusercontent.com/26581253/52792986-f9f9a700-306c-11e9-9015-e0775aa8ae2e.png)

**Note: I tried to increase the timeout to 240 seconds, but the printer finishes its work and I still get this error.**

**Note: The printer use Marlin firmware.**

Help me please 🙂  

# **Update** 

I update my firmware version to marlin v1.1.8 !

With same GCode commands i get this data format now => 

````
Send: G28
[...]
Recv: X:116.00 Y:139.00 Z:6.40 E:0.00 Count X:9454 Y:11329 Z:16496
Recv: ok
Send: M155 S30
Recv: ok
Send: G29 T
[...]
Recv: 
Recv: Bed Height Topography:
Recv:    +--- BACK --+
Recv:    |           |
Recv:  L |    (+)    | R
Recv:  E |           | I
Recv:  F | (-) N (+) | G
Recv:  T |           | H
Recv:    |    (-)    | T
Recv:    |           |
Recv:    O-- FRONT --+
Recv:  (0,0)
Recv:  -0.17623 -0.17623 +0.02901
Recv:  -0.06643 +0.02125 +0.22533
Recv:  -0.15799 -0.07109 +0.37237
Recv: 
Recv: X:193.02 Y:185.99 Z:6.40 E:0.00 Count X:15730 Y:15159 Z:16545
Recv: ok
Send: M155 S3
Recv: ok
````

And so I went to see the octoprint log and I have this error => 
````
2019-02-14 19:25:59,855 - octoprint.util.comm - ERROR - Error while processing hook bedlevelvisualizer:
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 2626, in _readline
    ret = hook(self, ret)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_bedlevelvisualizer/__init__.py", line 123, in processGCODE
    z = a[2].reshape((len(x),len(y)))
IndexError: index 2 is out of bounds for axis 0 with size 2
````

Has anyone ever had this error? 🙂

**Comment by MathieuAndrade** [comment]
A restart of the raspberry and the printer was enough to solve the problem ... do not ask me why 🤔 
But now its works !!
Thanks 😁
