### ISSUE TITLE
[BUG]: Bed Visualizer Not Reading Reported Data

### ISSUE THREAD

**Issue by TrevSaysHi** [jneilliii/OctoPrint-BedLevelVisualizer#318]
Hello! I have an ender 3 pro with a bltouch sensor installed, the firmware im using is the one provided by creality from the youtube channel, I am trying to use the bed visualizer but am getting some weird results,
I have simple settings 
```
G28
@BEDLEVELVISUALIZER
G29 T
```

and I get back this in the terminal
```
Recv: Bilinear Leveling Grid:
Recv:       0      1      2
Recv:  0 -1.775 -0.943 -0.120
Recv:  1 +0.253 +0.968 +1.210
Recv:  2 +2.195 +2.872 +3.142
```

for some reason the four corners arent getting saved to the bed visualizer the current mesh data is 
```
-100     NaN     -0.943     NaN
0     0.253     0.968     1.210
100     NaN     2.872     NaN
    -100     0     100
```

I will attach the log, from doing a quick look the issue seems to be here.
```
2020-11-09 22:18:28,097 - octoprint.util.comm - ERROR - Error while processing hook bedlevelvisualizer:
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 2952, in _readline
    ret = hook(self, ret)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_bedlevelvisualizer/__init__.py", line 327, in process_gcode
    self.mesh[~circle_mask] = None
ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 
2020-11-09 22:18:28,113 - octoprint.util.comm - INFO - Telling the printer to set the busy interval to our "communicationBusy" timeout - 1s = 2s
2020-11-09 22:18:28,130 - octoprint.util.comm - ERROR - Error while processing hook bedlevelvisualizer:
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 2952, in _readline
    ret = hook(self, ret)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_bedlevelvisualizer/__init__.py", line 327, in process_gcode
    self.mesh[~circle_mask] = None
ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 
```

Here is the log from plugin_bedlevelvisualizer_debug.log
```
[2020-11-09 21:26:56,610] DEBUG: mesh collection started
[2020-11-09 21:28:31,922] DEBUG: [u'-1.775', u'-0.943', u'-0.120']
[2020-11-09 21:28:31,926] DEBUG: [u'+0.253', u'+0.968', u'+1.210']
[2020-11-09 21:28:31,930] DEBUG: [u'+2.195', u'+2.872', u'+3.142']
[2020-11-09 21:28:32,053] DEBUG: {'z_min': 0, 'y_min': 0, 'x_max': 200.0, 'x_min': 0, 'type': 'circular', 'y_max': 200.0, 'z_max': 200.0}
[2020-11-09 21:28:32,053] DEBUG: stopping mesh collection
[2020-11-09 21:28:32,059] DEBUG: [[u'None', u'-0.943', u'None'], [u'+0.253', u'+0.968', u'+1.210'], [u'None', u'+2.872', u'None']]
[2020-11-09 21:28:32,060] DEBUG: [[u'None', u'-0.943', u'None'], [u'+0.253', u'+0.968', u'+1.210'], [u'None', u'+2.872', u'None']]
[2020-11-09 22:16:53,088] DEBUG: mesh collection started
[2020-11-09 22:18:27,961] DEBUG: [u'-1.780', u'-0.943', u'-0.078']
[2020-11-09 22:18:27,967] DEBUG: [u'+0.047', u'+1.090', u'+1.610']
[2020-11-09 22:18:27,971] DEBUG: [u'+1.865', u'+3.070', u'+3.892']
[2020-11-09 22:18:28,090] DEBUG: {'z_min': 0, 'y_min': 0, 'x_max': 200.0, 'x_min': 0, 'type': 'circular', 'y_max': 200.0, 'z_max': 200.0}
[2020-11-09 22:18:28,091] DEBUG: stopping mesh collection
[2020-11-09 22:18:28,124] DEBUG: {'z_min': 0, 'y_min': 0, 'x_max': 200.0, 'x_min': 0, 'type': 'circular', 'y_max': 200.0, 'z_max': 200.0}
[2020-11-09 22:18:28,125] DEBUG: stopping mesh collection
```

[octoprint.log](https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails/files/5513603/octoprint.log)
[plugin_bedlevelvisualizer_debug.log](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/5513635/plugin_bedlevelvisualizer_debug.log)

**Comment by TrevSaysHi** [comment]
Mistake on my part printer was set to circular bed
